qcsys/admin/routes.py
# -*- coding:utf8 -*-
#encoding = utf-8

from flask import Blueprint, flash, redirect, url_for, session, request, render_template, jsonify
from functools import wraps
from wtforms import Form, StringField, TextAreaField, validators,SelectField, SelectMultipleField,\
                    IntegerField, DecimalField
from wtforms.fields.html5 import DateField
from datetime import datetime
from ..views import mysql
from math import ceil

adminApp = Blueprint('admin', __name__,
                     template_folder='templates',
                     static_folder='static'
                     )


# ##### Global variable and functions #####
# Check if user logged in
def is_logged_in(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            flash('Unauthorized, Please login', 'danger')
            return redirect(url_for('index'))
    return wrap

# user type
user_type = [('guide', '导游'), ('driver', '司机'), ('agent', '代理'),('bus', '巴士'),('hotel', '酒店'), ('other', '其他')]
# case status
case_status = [('new','新投诉'),('processing','处理中'),('w_response','等待回复'),('w_confirm','等待确认'),('w_email','等待邮件'),
               ('report','反映情况'),('solved','已解决'),('cancel','投诉取消'), ('terminated','投诉终止')]
# departments and bill to items
dept_category = [('hotel','酒店部'),('trans','运输部'),('guide','导游部'),('ec','美东部'),
                 ('local', 'local部'), ('eci', 'ECI部'),('cruise','邮轮部'),('sales','销售部'),
                 ('ticket', '票务部'), ('mkting', '市场部'),('chi','芝加哥分部'),('dc','华盛顿分部'),
                 ('orlando', '奥兰多分部'), ('mia', '迈阿密分部'),('sea','西雅图分部'),('texas','德州分部'),
                 ('spcl', '特殊案例'), ('other', '其他地接'), ('it', 'IT部'), ('acc', '会计部'),
                 ('na', '待输入'), ('bos', '波士顿分部'), ('ap', '接机部')]

# case source select items
case_source_s = [('phone_a', '代理致电'), ('email_a', '代理发邮件'), ('phone_c', '客人致电'), ('email_c', '客人发邮件'),
                 ('phone_e', '内部同事致电'), ('email_e', '内部同事发邮件'), ('wechat', '微信投诉')]

# responsible party select items
case_resp_party_s = [('agent', '代理'), ('uv', '纵横'), ('customer', '客人'), ('uvc', '纵横和客人'), ('uva', '纵横和代理'), ('uvac', '纵横和客人和代理'), ('other', '第四方'), ('na', '待输入')]

# case reference select items
case_reference_s = [('compensation', '赔偿方案'), ('compensation final', '赔偿方案终极'), ('more', '多'), ('less', '少'), ('na', '待输入')]

# customer satisfaction select items
case_satisfaction_s = [('acceptance', '接受赔偿'), ('great', '非常满意'), ('good', '满意'), ('displeasure', '不满意'), ('catastrophic', '非常不满'), ('na', '待输入')]

# payment method select items
case_payment_s = [('credit', 'Credit Memo'), ('quickpay', 'Quickpay'), ('cb', '中国的银行'), ('ub', '美国的银行'),
                  ('check', '支票'), ('bill', 'Billed'), ('tt', 'TT'), ('rtt', 'Refunded By TT'), ('GRF', '导游退款'),
                  ('other', '其他'), ('na', '待输入')]

# other info type select items
other_type_list = [('bus', '巴士'), ('hotel', '酒店'), ('tic', '门票'), ('other', '其他')]

# get user list
def getting_user_list(table_name, user_type):
    cur = mysql.connection.cursor()
    if table_name == 'acct_mgmt':
        result = cur.execute("SELECT username FROM acct_mgmt WHERE is_using=1 AND username NOT IN ('admin')")
    elif table_name == 'user_mgmt' and user_type != 'all':
        str = "SELECT id,name FROM user_mgmt WHERE is_using=1 AND type='{}'".format(user_type)
        result = cur.execute(str)
    elif table_name == 'user_mgmt' and user_type == 'all':
        result = cur.execute("SELECT id, name FROM user_mgmt WHERE is_using=1")
    else:
        result = 0

    if result > 0:
        listItems = cur.fetchall()
        cur.close()
        return listItems
    else:
        cur.close()
        return 0

def user_select_list(table_name, user_type):
    userlist = []
    itemlist = getting_user_list(table_name, user_type)
    if itemlist != 0:
        if table_name == 'acct_mgmt':
            for item in itemlist:
                userlist.append((item['username'],item['username']))
            return  userlist
        elif table_name == 'user_mgmt' and user_type != 'all':
            for item in itemlist:
                userlist.append((str(item['id']),item['name']))
            return userlist
        elif table_name == 'user_mgmt' and user_type == 'all':
            for item in itemlist:
                userlist.append((str(item['id']),item['name']))
            return userlist
        else:
            return 0
    else:
        return 0

def transferContent(content):
    if content is None:
        return None
    else:
        string = ""
        for c in content:
            if c == '"':
                string += '\\\"'
            elif c == "'":
                string += "\\\'"
            elif c == "\\":
                string += "\\\\"
            else:
                string += c
        return string


# ##### Global variable and functions end #####


@adminApp.route('/')
@is_logged_in
def index():
    return render_template('home.html')



# ##### label begin #####
class label(Form):
    title = StringField('标签名', [validators.length(min=1, max=100),validators.InputRequired(message='标签名必填！')])
    under = StringField('所属标签')
    comments = TextAreaField('中文回复范例')
    comments_eng = TextAreaField('英文回复范例')


@adminApp.route('/labels', defaults={'pagenum': 1})
@adminApp.route('/labels&page=<int:pagenum>')
@is_logged_in
def labels(pagenum):
    pages = int(pagenum) -1

    pageCur = mysql.connection.cursor()
    totalResults = pageCur.execute("SELECT * FROM label_mgmt WHERE level=1")
    totalPages = totalResults / 10
    pageCur.close()

    cur = mysql.connection.cursor()
    result = cur.execute("SELECT * FROM label_mgmt WHERE level=1 LIMIT %s,%s", (pages * 10, 10))
    if result > 0:
        listItems = cur.fetchall()
        cur.close()
        return render_template('labels.html', labels=listItems, pages=ceil(totalPages))
    else:
        cur.close()
        msg = 'No Content Found'
        return render_template('labels.html', msg=msg)


@adminApp.route('/childlabels&<string:title>', defaults={'pagenum': 1})
@adminApp.route('/childlabels&<string:title>&page=<int:pagenum>')
@is_logged_in
def child_labels(pagenum,title):
    pages = int(pagenum) -1
    pageCur = mysql.connection.cursor()
    totalResults = pageCur.execute("SELECT * FROM label_mgmt WHERE parent=%s", [title])
    totalPages = totalResults / 10
    pageCur.close()

    cur = mysql.connection.cursor()
    result = cur.execute("SELECT * FROM label_mgmt WHERE parent=%s LIMIT %s,%s", ( title, pages * 10, 10))
    if result > 0:
        listItems = cur.fetchall()
        cur.close()
        return render_template('childlabels.html', labels=listItems, pages=ceil(totalPages),parent=title)
    else:
        cur.close()
        msg = 'No Content Found'
        return render_template('childlabels.html', msg=msg, pages=0, parent=title)


@adminApp.route('/addlabel', methods=['GET', 'POST'])
@is_logged_in
def add_label():
    form = label(request.form)

    if request.method == 'POST' and form.validate():
        title = form.title.data
        level = 1
        parent = '0'
        comments = transferContent(form.comments.data)
        comments_eng = transferContent(form.comments_eng.data)
        # Create Cursor
        cur = mysql.connection.cursor()
        # Execute
        cur.execute("INSERT INTO label_mgmt (title, level, parent, comments, comments_eng) VALUES(%s,%s,%s,%s,%s)",
                    (title, level, parent, comments, comments_eng))
        # commit to db
        mysql.connection.commit()
        # close connection
        cur.close()

        flash('New Content Created', 'success')
        return redirect(url_for('admin.labels'))

    return render_template('addlabel.html', form=form, parent=0)

@adminApp.route('/addchildlabel&<string:pt>', methods=['GET', 'POST'])
@is_logged_in
def add_child_label(pt):
    form = label(request.form)
    under_label = 'NULL'
    if request.method == 'POST' and form.validate():
        title = form.title.data
        parent = pt
        level = 2
        if form.under.data != '':
            under_label = form.under.data
        comments = transferContent(form.comments.data)
        comments_eng = transferContent(form.comments_eng.data)
        # Create Cursor
        cur = mysql.connection.cursor()
        # Execute
        cur.execute("INSERT INTO label_mgmt (title, level, parent, comments, comments_eng, under) VALUES(%s,%s,%s,%s,%s,%s)",
                    (title, level, parent, comments, comments_eng, under_label))
        # commit to db
        mysql.connection.commit()
        # close connection
        cur.close()

        flash('New Content Created', 'success')
        return redirect(url_for('admin.child_labels',pagenum=1,title=pt))

    return render_template('addlabel.html', form=form, parent=pt)

@adminApp.route('/editlabel/<string:labelNum>&', methods=['GET', 'POST'], defaults={'parent': 0})
@adminApp.route('/editlabel/<string:labelNum>&<string:parent>', methods=['GET', 'POST'])
@is_logged_in
def edit_label(labelNum, parent):
    form = label(request.form)
    under_label = 'NULL'
    if request.method == 'GET':
        # Create Cursor
        cur = mysql.connection.cursor()
        # Execute
        result = cur.execute("SELECT * FROM label_mgmt WHERE label_num = %s", [labelNum])
        sinContent = cur.fetchone()

        form.title.data = sinContent['title']
        form.comments.data = sinContent['comments']
        form.comments_eng.data = sinContent['comments_eng']
        form.under.data = sinContent['under']
        # close connection
        cur.close()
        return render_template('addlabel.html', form=form, parent=parent)

    elif request.method == 'POST' and form.validate():
        title = form.title.data
        comments = transferContent(form.comments.data)
        comments_eng = transferContent(form.comments_eng.data)
        if form.under.data != '':
            under_label = form.under.data

qcsys/admin/templates/addlabel.html
{% extends 'layout.html'%}

{% block body %}
<h3 class="text-primary">标签编辑</h3>
     {% from "includes/_formhelpers.html" import render_field %}
    <form action="" method="post">
        <div class="form-group">
            {{render_field(form.title, class_="form-control")}}
        </div>
        {% if parent != '0' and parent != 0 %}
        <div class="form-group">
            {{render_field(form.under, class_="form-control", id="under_label")}}
        </div>
        {% endif%}
        <div class="form-group">
            {{render_field(form.comments, class_="form-control" )}}
        </div>
        <div class="form-group">
            {{render_field(form.comments_eng, class_="form-control" )}}
        </div>
        <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Submit">
        <a href="/admin/labels" class="btn btn-danger pull-right">返回</a>
        </div>
    </form>
{% endblock %}

qcsys/admin/templates/adduser.html
{% extends 'layout.html'%}

{% block body %}
<h3 class="text-primary">人员编辑</h3>
<br>
     {% from "includes/_formhelpers.html" import render_field %}
    <form action="" method="post">
        <div class="form-group">
            {{render_field(form.name, class_="form-control")}}
        </div>
        <div class="form-group">
            {{render_field(form.type, class_="form-control" )}}
        </div>
        <div class="form-group">
            {{render_field(form.remark, class_="form-control" )}}
        </div>
        <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Submit">
        <a href="/admin/users" class="btn btn-danger pull-right">返回</a>
        </div>
    </form>
{% endblock %}

qcsys/admin/templates/caseattachment.html
{% extends 'layout.html'%}

{% block body %}
{% if attachments %}
    <table class="table table-active">
        <h4 class="text-primary">案例 #{{qc_num}}附件</h4>
        <thead class="thead-dark">
            <tr>
              <th scope="col">附件名</th>
              <th scope="col">附件URL</th>
              <th scope="col">提交日期</th>
              <th scope="col">备注</th>
              <th scope="col">操作</th>
            </tr>
        </thead>
        <tbody>
    {% for attach in attachments %}
            <tr>
              <td>{{attach.name}}</td>
              <td><a href="{{attach.url}}" target="_blank">点我~</a></td>
              <td>{{attach.date}}</td>
              <td width="40%">{{attach.comment}}</td>
              <td>
                 <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#attachment_delete" data-qcID="{{attach.id}}&{{qc_num}}">删除</button>
              </td>
            </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p class="text-info">该案例还未添加附件，请在下面添加。</p>
{% endif %}

<h4 class="text-primary font-weight-bold">添加附件</h4>
<hr class="my-4">
{% from "includes/_caseformhelper.html" import render_field %}
<form action="" method="post">
    <div class="form-group row">
      {{render_field(form.name, class_="form-control", rows="6")}}
  </div>
    <div class="form-group row">
      {{render_field(form.url, class_="form-control")}}
  </div>
    <div class="form-group row">
      {{render_field(form.comments, class_="form-control")}}
  </div>
  <div class="form-group row mx-auto">
    <div class="col-sm-5">
      <input type="submit" class="btn btn-primary btn-block" value="提交">
    </div>
      <div class="col-sm-5">
          <a href="/admin/caselist" class="btn btn-danger btn-block">返回</a>
      </div>
  </div>
</form>


<div class="modal fade" id="attachment_delete" tabindex="-1" role="dialog" aria-labelledby="delete_attach" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger" id="delete_attch">警告！</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        真的要删除吗？真的要吗？大侠手下留情啊！(wei wan chen)
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">那就不删~</button>
        <a href="/admin/deleteattachment/" class="btn btn-danger" id="del_c_attach">狠心删除！</a>
      </div>
    </div>
  </div>
</div>


{% endblock %}

qcsys/admin/templates/caselabels.html
{% extends 'layout.html'%}

{% block body %}

{% if labels %}
    <table class="table table-active">
        <h4 class="text-primary">已有分类</h4>
        <thead class="thead-dark">
            <tr>
              <th scope="col">部门</th>
              <th scope="col">标签名</th>
              <th scope="col">回复范例</th>
              <th scope="col">Response Example</th>
              <th scope="col">操作</th>
            </tr>
        </thead>
        <tbody>
    {% for label in labels %}
            <tr>
                {% if label.parent_title == 0 %}
              <td>{{label.title}}</td>
                {% else %}
              <td>{{label.parent_title}}</td>
                {% endif %}
              <td>{{label.title}}</td>
              <td><textarea rows="6" cols="58">{{label.comments}}</textarea></td>
              <td><textarea rows="6" cols="58">{{label.comments_eng}}</textarea></td>
              <td>
                 <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#label_delete" data-qcID="{{label.qc_num}}:{{label.title}}:{{label.parent_title}}">删除</button>
              </td>
            </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p class="text-info">该案例还未分类，请在下面添加。</p>
{% endif %}
<hr class="my-4 style2">

<form action="" method="post">
    <h4 class="text-primary">添加分类标签</h4>
    <hr class="my-2">

    <div class="form-group row">
      <div class="col-sm-10">
        <div class="input-group mb-3">
          <input type="text" id="item-labels" class="form-control" placeholder="Labels" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-info" type="button" id="submitbt-labels">添加标签</button>
          </div>
        </div>
        <div class="card " style="width: 45rem;">
          <div class="card-body" id="labelitems">
          </div>
        </div>
      </div>
     </div>
    <hr class="my-5">
    <div class="form-group row mx-auto">
    <div class="col-sm-5">
      <input type="submit" class="btn btn-primary btn-block" value="提交">
    </div>
      <div class="col-sm-5">
          <a href="/admin/caselist" class="btn btn-danger btn-block">返回</a>
      </div>
    </div>
    </form>

<div class="modal fade" id="label_delete" tabindex="-1" role="dialog" aria-labelledby="delete_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger" id="delete_label">警告！</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        真的要删除吗？真的要吗？大侠手下留情啊！
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">那就不删~</button>
        <a href="/admin/deletecaselabel/" class="btn btn-danger" id="del_c_label">狠心删除！</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

qcsys/admin/templates/caselist.html
{% extends 'layout.html'%}

{% block body %}
<form action="/admin/casesearch" method="post" name="search_case">
    <div class="input-group margin-bottom-sm">
        <span class="input-group-addon"><i class="fa fa-search fa-fw"></i></span>
        <input id="casesearch" class="form-control" type="text" name="search_case" placeholder="输入投诉编号/invoice#/订单号来搜索" value={{request.form.search_case}}>
        <input type="submit" class="btn btn-primary" value="Search">
    </div>
</form>
<br>
<div class="container">
    <div class="row justify-content-start">
        <div class="col-2">
            <div class="dropdown show">
              <a class="btn btn-info dropdown-toggle" href="#" role="button" id="statusdrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                请选择投诉状态
              </a>
                <div class="dropdown-menu" aria-labelledby="statusdrop">
                    <a class="dropdown-item" href="caselist&page=1&new">新投诉</a>
                    <a class="dropdown-item" href="caselist&page=1&processing">处理中</a>
                    <a class="dropdown-item" href="caselist&page=1&w_response">等待回复</a>
                    <a class="dropdown-item" href="caselist&page=1&w_confirm">等待确认</a>
                    <a class="dropdown-item" href="caselist&page=1&w_email">等待邮件</a>
                    <a class="dropdown-item" href="caselist&page=1&report">反映情况</a>
                    <a class="dropdown-item" href="caselist&page=1&solved">已解决</a>
                    <a class="dropdown-item" href="caselist">全部</a>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="my-3">
<h3 class="text-primary">投诉案件列表</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">投诉编号</th>
      <th scope="col">案件状态</th>
      <th scope="col">创建时间</th>
      <th scope="col">代理商</th>
      <th scope="col">Invoice#</th>
      <th scope="col">操作</th>
    </tr>
  </thead>
  <tbody>
    {% for case in caseinfos %}
    <tr>
        <th scope="row"><a href="casedetails/{{case.qc_num}}">{{case.qc_num}}</a></th>
        <td class="">
            <a role="button" class="btn btn-outline-danger btn-sm text-danger" data-toggle="modal" data-target="#c_status" data-qcID="{{case.qc_num}}">
                {{ {"processing": "处理中", "new": "新投诉", "w_response": "等待回复", "w_confirm": "等待确认", "w_email": "等待邮件", "report": "反映情况", "solved": "已解决", "cancel": "投诉取消", "terminated": "投诉终止"}[case.status] | default("New") }}
            </a>
        </td>
        <td>{{case.creat_date}}</td>
        <td style="width: 170px;">{{case.name}}</td>
        <td>{{case.invoice}}</td>
        <td>
            <div class="btn-group" role="group">
                <a href="caselabels/{{case.qc_num}}" class="btn btn-primary btn-sm">案例归类</a>
                <a href="editcase/{{case.qc_num}}" class="btn btn-info btn-sm">编辑案例</a>
                <a href="caseattachment/{{case.qc_num}}" class="btn color_attach btn-sm">附件管理</a>
                <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#c_processing" data-qcID="{{case.qc_num}}">处理进度</button>
                <a href="caseresult/{{case.qc_num}}" class="btn btn-success btn-sm">处理结果</a>
                <a href="caseotherinfo/{{case.qc_num}}" class="btn btn-dark btn-sm">其他信息</a>
            </div>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<nav aria-label="Page navigation example">
  <ul class="pagination">
      <li class="page-item"><a class="page-link" href="/admin/caselist&page=1&{{status}}">Frist page</a></li>
      {% if pages <= 3 %}
      {% for page in range(pages) %}
        <li class="page-item"><a class="page-link" href="/admin/caselist&page={{page + 1}}&{{status}}">{{page + 1}}</a></li>
      {% endfor %}
      {% else %}
        <div class="dropdown show" style="padding-right:10px; padding-left:10px;">
          <a class="btn page-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Go to Page...
          </a>

          <div class="dropdown-menu scrollable-Drop-menu" aria-labelledby="dropdownMenuLink">
            {% for page in range(pages) %}
            <a class="page-link" href="/admin/caselist&page={{page + 1}}&{{status}}">{{page + 1}}</a>
            {% endfor %}
          </div>
        </div>

      {% endif %}
      <li class="page-item"><a class="page-link" href="/admin/caselist&page={{pages}}&{{status}}">Last page</a></li>
  </ul>
</nav>


<div class="modal fade" id="c_status" tabindex="-1" role="dialog" aria-labelledby="statusModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary" id="statusModal">修改状态</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/admin/changestatus" method="post" name="change_status">
          <div class="form-group">
            <label for="status_select" class="col-form-label">请选择投诉状态:</label>
            <select class="form-control" id="status_select" name="s_status">
                <option value="processing">处理中</option>
                <option value="w_response">等待回复</option>
                <option value="w_confirm">等待确认</option>
                <option value="w_email">等待邮件</option>
                <option value="report">反映情况</option>
                <option value="solved">已解决</option>
                <option value="cancel">投诉取消</option>
                <option value="terminated">投诉终止</option>
            </select>
          </div>
          <div class="form-group">
            <label for="status-message-text" class="col-form-label">修改理由: <spam class="text-danger font-weight-bold">*必填</spam></label>
            <textarea class="form-control" id="status-message-text" name="s_message_t" required></textarea>
          </div>
            <input type="hidden" id="qcid-value" name="s_qc_id" value="null">
            <input type="hidden" name="s_qc_id" value="null">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">返回</button>
            <input type="submit" class="btn btn-primary pull-right" value="提交">
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="c_processing" tabindex="-1" role="dialog" aria-labelledby="processingModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary" id="processingModal">处理进度</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/admin/caseprocessing" method="post" name="change_processing">
          <div class="form-group">
            <label for="status-message-text" class="col-form-label">本次处理结果<spam class="text-danger font-weight-bold">*必填</spam></label>
            <textarea rows="15" class="form-control" id="processing-message-text" name="p_message_t" required></textarea>
          </div>
            <input type="hidden" id="qcid-value-p" name="p_qc_id" value="null">
            <input type="hidden" name="p_qc_id" value="null">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">返回</button>
            <input type="submit" class="btn btn-primary pull-right" value="提交">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

qcsys/admin/templates/home.html
{% extends 'layout.html'%}

{% block body %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{{session.username}}</h1>
      <hr class="my-3">
      <p class="lead">欢迎来到美妙的投诉世界！！</p>
      <p class="text-md-right text-secondary">投诉案例管理系统  Beta v0.9</p>
      <p class="text-md-right text-secondary"><i class="fa fa-copyright" aria-hidden="true"></i>UV IT Dept 2017-2018</p>
  </div>
</div>
{% endblock %}

qcsys/admin/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UV QC</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('admin.static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('admin.static', filename='css/style.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('admin.static', filename='css/jquery-ui.min.css')}}">
</head>
<body>

    {% include 'includes/_navbar.html' %}
    <div class="container-fluid">
        <div class="row" style="padding-right:10px;">
            <div class="col-sm-2 col-md-1 col-lg-1" style="padding-left:0px;">
               {% include 'includes/_sidebar.html' %}
            </div>
            <div id="main_con">
                {% include 'includes/_messages.html' %}
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js')}}" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}" ></script>
    <script src="{{ url_for('admin.static', filename='js/sidebar.js')}}" ></script>
    <script src="{{ url_for('static', filename='js/jquery-ui.min.js')}}" ></script>
    <script src="{{ url_for('admin.static', filename='js/ajax.js')}}" ></script>
    <script src="{{ url_for('admin.static', filename='js/utility.js')}}" ></script>
    <script>
        $(function() {
            $("#autocomplete").autocomplete({
                source:function(request, response) {
                    $.getJSON("{{url_for('admin.index')}}",{
                        q: request.term, // in flask, "q" will be the argument to look for using request.args
                    }, function(data) {
                        console.log(data.matching_result);
                        response(data.matching_result); // matching_results from jsonify
                    });
                },
                minLength: 1,
                select: function(event, ui) {
                    console.log(ui.item.value); // not in your question, but might help later
                }
            });
        })

        function off() {
            document.getElementById("overlay").style.display = "none";
        }
    </script>
</body>
</html>